### ISSUE TITLE
Undefined method `cvv_path'

### ISSUE THREAD

**Issue by joyboy67** [solidusio-contrib/solidus_stripe#130]
Hello I use Solidus (3.2.2) with solidus_starter_frontend, I added manually the solidus_stripe's frontend views to the app and I get this error in the checkout payment step

```
NoMethodError in Spree::Checkout#edit

Showing /home/computer/shop/app/views/spree/checkout/payment/v3/_form_elements.html.erb where line #29 raised:

undefined method `cvv_path' for #<ActionDispatch::Routing::RoutesProxy:0x00000c8ef6aa4ad8 @scope=#<Spree::CheckoutController:0x0000000006dc90>, @routes=#<ActionDispatch::Routing::RouteSet:0x00000c8e63c8a700>, @helpers=#<Module:0x00000c8f1697d428>, @script_namer=#<Proc:0x00000c8e98e82500 /usr/local/lib/ruby/gems/3.1/gems/actionpack-7.0.4/lib/action_dispatch/routing/mapper.rb:653 (lambda)>>



  <%= label_tag "card_cvc", t('spree.card_code') %>
  <div id="card_cvc"></div>
  <%= link_to "(#{t('spree.what_is_this')})", spree.cvv_path, target: '_blank', "data-hook" => "cvv_link", id: "cvv_link" %>
</div>

<div id="card-errors" class='errorExplanation' role="alert" style="display: none"></div>

```

**Comment by kennyadsl** [comment]
Hello @joyboy67! Those views are specific for the legacy frontend, where the `cvv_path` was defined in the routes. You have two options:

1. Define your own `cvv_path` in your routes as you would do in any other rails application. You can let it point to a static page where you explain what a CVV is. 
2. Remove that part from the view. To be honest, nowadays it's pretty uncommon to explain what a CVV is to people. I saw you already copied the view into your own store, removing that part should be straightforward. 

Let me know if that helps!

**Comment by joyboy67** [comment]
Yes it helps, thank you @kennyadsl ;)
