### ISSUE TITLE
A token may not be passed in as a PaymentMethod. Instead, create a PaymentMethod or convert your token to a PaymentMethod by setting the `card[token]`

### ISSUE THREAD

**Issue by joyboy67** [solidusio-contrib/solidus_stripe#131]
Hello I use solidus_stripe (4.3.0) with v3 Elements and v3 Intents, when I try to make a payment I get (from the Stripe API ?) `A token may not be passed in as a PaymentMethod. Instead, create a PaymentMethod or convert your token to a PaymentMethod by setting the 'card[token]'`

**ENV**

Solidus Version: 3.2.2
Frontend: solidus_starter_frontend
Env: development mode
Rails version: 7.0.4

**Comment by waiting-for-dev** [comment]
Hey @joyboy67, which frontend are you using? solidus_starter_frontend or solidus_frontend?

**Comment by joyboy67** [comment]
> Hey @joyboy67, which frontend are you using? solidus_starter_frontend or solidus_frontend?

Hey, I use solidus_starter_frontend

I copied manually the frontend's views into the app `app/views/spree` because https://github.com/solidusio/solidus_stripe/issues/127 and added `//= require jquery3` to `vendor/assets/javascripts/spree/frontend/all.js` (https://github.com/solidusio/solidus/discussions/4623)

**Comment by waiting-for-dev** [comment]
@joyboy67, does https://github.com/solidusio/solidus_stripe/issues/71#issuecomment-736282633 fix your issue?

**Comment by joyboy67** [comment]
Ah I don't see this issue, yes it's fix thank you @waiting-for-dev ;)
