### ISSUE TITLE
Integrate Payment Element

### ISSUE THREAD

**Issue by elia** [solidusio-contrib/solidus_stripe#142]
We want to start from the [Payment Element](https://stripe.com/docs/payments/payment-element) which comes with support for multiple payment methods, while still working well in the classic step-based checkout featured in SSF (vs. switching to the fully external Stripe Checkout).

We need to setup the simplest possible integration and document all the steps required for setting up the development environment and using the Stripe sandbox.

- [x] Blocked by #141 
- [ ] Spike: #147 

### Subtasks

- [x] #151
- [x] #152
- [x] #153
- [x] #154
- [x] #148
- [x] #149
- [x] #150

### After all is done

- [ ] final check on documentation 
- [ ] stripe option for solidus_installer

**Comment by chrean** [comment]
We are tracking this on single tasks instead of keeping this one as a container.
Closing.
