### ISSUE TITLE
Add test for the integration with `solidus_backend`

### ISSUE THREAD

**Issue by elia** [solidusio-contrib/solidus_stripe#150]
## What 

QA the backend integration, make sure all the necessary partials and behaviors are there and work as expected.
Add missing specs to cover any regular or edge case.

```[tasklist]
### Test cases
- [x] refunding a payment
- [x] voiding a payment
- [x] canceling an order
- [ ] https://github.com/solidusio/solidus_stripe/issues/266
- [x] navigating payments
- [x] inspecting/rendering log entries
```

## Why

It's likely that once finished we'll still have some edge cases to cover, this is meant as a final QA that should be done before releasing.

**Comment by jakepenn** [comment]
Is there an integration with the payment element on a branch somewhere? I'm interested in using this in our shop at the moment

**Comment by elia** [comment]
@jakemumu yes, master is tracking that work, but it's still being heavily changed, especially where it maps models between stripe and solidus. Anyway [one of the next PRs](https://github.com/solidusio/solidus_stripe/pull/158) should put it into a relatively more stable state.
