### ISSUE TITLE
Simplify the generated code to configure the preference sources

### ISSUE THREAD

**Issue by waiting-for-dev** [solidusio-contrib/solidus_stripe#170]
## Why

[The fix](https://github.com/solidusio/solidus/pull/4858) is being back ported to all supported solidus versions.

## What

No need to [use `.to_prepare`](https://github.com/solidusio/solidus_stripe/blob/5d19132d568ea3a40f3dde5c2aafce9a657acae3/lib/generators/solidus_stripe/install/templates/config/initializers/solidus_stripe.rb#L17) as per https://github.com/solidusio/solidus/pull/4858

**Comment by elia** [comment]
Fixed by #206
