### ISSUE TITLE
Track webhook intent events as Solidus log entries on the corresponding payment

### ISSUE THREAD

**Issue by elia** [solidusio-contrib/solidus_stripe#171]
## Why

We want a local copy of the events affecting a given stripe payment, so to aid debugging payments (e.g. customer service trying to shed light on order issues).

## What

Add log entries for each payment transition handled by the intents controller.

```[tasklist]
### Dependencies
- [ ] Blocked by #160 
- [ ] Blocked by #154
```

**Comment by loicginoux** [comment]
Does this belong to a record in a Spree::LogEntry ? Should we just store it or is there more logic around it ? Should it be displayed somehow in admin ?

**Comment by elia** [comment]
@loicginoux yes, it's related to LogEntry, to which Spree::Payment is connected. In terms of showing the entries they are already visible through the admin in the details page of the payment, although there's surely room for improvement.

**Comment by elia** [comment]
We agreed to add log entries for all webhooks involving payments from within the individual webhooks issues.
