### ISSUE TITLE
Being able to customize the Stripe::PaymentIntent creation parameters

### ISSUE THREAD

**Issue by loicginoux** [solidusio-contrib/solidus_stripe#173]
**Desired Behavior**

Currently payment intent is created with basic options ([see code](https://github.com/solidusio/solidus_stripe/blob/master/app/controllers/solidus_stripe/payment_intents_controller.rb#L19)) 
It would be good to support a way to customize it easily. There are a lot more options in Stripe doc for intent creation and people will want to use them at some point.
I Imagine, at least to have the Hash parameter extracted in a controller method (easily overwritten) or in a separate service like the example from [this PR](https://github.com/solidusio/solidus_stripe/pull/121/files#diff-731d975f879e89e2da5e248ccdfdcf53d9aebf9a8d5add2289218a32f23b2627)

**Comment by elia** [comment]
@loicginoux `#prepare_for_payment` will create a payment intent if missing and accepts a hash that will be forwarded to the payment intent creation, would that be enough for you?

https://github.com/solidusio/solidus_stripe/blob/4bcc604d48f3f62e5d984b3c75b9a447eee3aa80/lib/generators/solidus_stripe/install/templates/app/views/orders/payment_info/_stripe.html.erb#L9

**Comment by loicginoux** [comment]
Yes I saw that, that resolves my issue ! Closing it. Thx
