### ISSUE TITLE
Unknown switches "--github" when trying to install dev env

### ISSUE THREAD

**Issue by loicginoux** [solidusio-contrib/solidus_stripe#174]
**To Reproduce**
Trying to install dev environment on solidus_stripe following the readme:
so 
- using the minimum reqired version: `rvm use 2.7.7`
- `bin/setup`
- and when `bin/dummy-app`

I see 
```
Unknown switches "--github"
Unknown switches "--path"
```

I understand that it comes from 
https://github.com/solidusio/solidus_stripe/blob/master/bin/dummy-app

and it seems like an issue with bundler, maybe I have the wrong version of bundler 
```
>bundle -v
`Bundler version 2.1.4`
```
**Expected behavior**
No error launching the dummy-app

**Comment by elia** [comment]
@loicginoux yes, those switches are available in more recent versions of rubygems/bundler, you can try using `gem update --system --no-document` (probably bundler 2.3 or higher) to update to the latest version for ruby 2.7, but in case it fails I suggest using a more recent version of ruby.

We're planning on expanding the supported versions, but for the sake of simplicity we'll do that afterwards and track that in the CI configuration: https://github.com/solidusio/solidus_stripe/blob/master/.circleci/config.yml#L87

**Comment by loicginoux** [comment]
Ok thanks, I am ok to have the issue closed if we consider that's a bad local setup.

**Comment by elia** [comment]
Closing, at least for the development setup I think it's fair to expect bundler to be up to date 👍
