### ISSUE TITLE
Support `auto_capture: true` for the payment method

### ISSUE THREAD

**Issue by elia** [solidusio-contrib/solidus_stripe#178]
## Why

Being able to auto_capture payments during the order completion is a stock solidus capability.

## What

Hook into the finalization process to capture the authorized amount for stripe payments that were previously authorized if `auto_capture` is enabled.

A possible implementation involves using a subscriber

```rb
# app/subscribers/update_account_balance_subscriber.rb
class SolidusStripe::AutoCaptureSubscriber
  include Omnes::Subscriber

  handle :order_finalized, with: :call

  def call(event)
    stripe_payments.each(&:capture!) # pseudo-code!
  end
end

# config/initializers/solidus_stripe.rb
Rails.application.config.to_prepare do
  SolidusStripe::AutoCaptureSubscriber.new.subscribe_to(Spree::Bus)
end
```

**Comment by waiting-for-dev** [comment]
We'll need to implement something like https://github.com/solidusio/solidus_stripe/pull/245 for the unhappy path

**Comment by rainerdema** [comment]
This seems to work fine with the current implementation.
Thanks to the implementation of the [`purchase` action with the "automatic" capture_method](https://github.com/solidusio/solidus_stripe/blob/6ecda67a456dd5d7ed08816b81470f98210c3ea8/app/models/solidus_stripe/gateway.rb#L89-L110), the authorization+capture happens correctly and is in line with the current Solidus logic.

As specified in the [`Spree::Payment::Processing` module](https://github.com/solidusio/solidus/blob/6d5580068d00c8fb711710a71e350e4c1358946c/core/app/models/spree/payment/processing.rb#L19-L21), if `auto_capture` is set to `true`, the purchase action will be invoked on the gateway of the referenced payment method.

I will do other checks, [follow Marc's suggestion about the unhappy path](https://github.com/solidusio/solidus_stripe/issues/178#issuecomment-1479410507) and implement the necessary specs to cover this use case.

**Comment by waiting-for-dev** [comment]
Does it also work for the payment intent flow? As I understand, `manual` [is fixed](https://github.com/solidusio/solidus_stripe/blob/c4d127e1a52454700ec9fc180716ed9dec3eabe6/app/models/solidus_stripe/payment_intent.rb#L58) now.
