### ISSUE TITLE
Update Stripe when a payment is failed on Solidus part

### ISSUE THREAD

**Issue by waiting-for-dev** [solidusio-contrib/solidus_stripe#185]
**Steps to reproduce**

- Proceed with a checkout until Stripe's payment form is rendered. At that point, Solidus has already created a `:processing` payment associated with the order (as we need the payment, which is bound to the Payment Intent, to render Stripe's Payment Element).
- Mark the payment as failed in the backend.
- Submit the form from the checkout with a valid card.

**Result**
Stripe authorizes the payment, while Solidus shows an error message because of trying to move a failed payment forward.

**Expected result**
Stripe has already marked that payment as invalid and we get the appropriate response.

**Considerations**
 It's not a very likely scenario, as just after the form is submitted in a normal flow, the payment will be marked as `:pending`, and the transition to `:failure` won't be possible anymore.

**Comment by rainerdema** [comment]
With the introduction of #249, we will no longer have a payment in the `payment` step but in the `confirm` one.
This payment will be in `checkout` state with no available actions for the admin.

https://user-images.githubusercontent.com/19948291/228614814-39bdf836-d42f-4f65-99b1-378740e8630d.mov

**Comment by waiting-for-dev** [comment]
Cool, @rainerdema! Does it mean we can close this one?

**Comment by rainerdema** [comment]
> Cool, @rainerdema! Does it mean we can close this one?

Yeah I think so 👍 I'm waiting to merge #249 before closing this one
