### ISSUE TITLE
Be resilient against duplicated webhook events

### ISSUE THREAD

**Issue by waiting-for-dev** [solidusio-contrib/solidus_stripe#188]
There's no guarantee that Stripe will send a webhook event only once (e.g., our server could timeout for the response while we've actually processed it; in that case, Stripe would retry). We need to ensure that we only process events once or that the subscribers are designed in an idempotent way.

Partially replaces #160

**Comment by loicginoux** [comment]
Not saying it's the definite solution but as discussed in https://github.com/solidusio/solidus_stripe/issues/189#issuecomment-1441957946 having an internal state machine and validating transitions might solve this problem as well...

**Comment by waiting-for-dev** [comment]
All of the webhook handlers we'll be shipping should be idempotent:

- `payment_intent.succeeded` will [do nothing](https://github.com/solidusio/solidus_stripe/blob/d86549b1225a4078855e7a648f58f8c61ed56d6d/app/subscribers/solidus_stripe/webhook/payment_intent_subscriber.rb#L27) if the payment is already completed.
- `payment_intent.payment_failed` will [do nothing](https://github.com/solidusio/solidus_stripe/blob/d86549b1225a4078855e7a648f58f8c61ed56d6d/app/subscribers/solidus_stripe/webhook/payment_intent_subscriber.rb#L52) if the payment is already canceled.
- `payment_intent.canceled` will [do nothing](https://github.com/solidusio/solidus_stripe/blob/d86549b1225a4078855e7a648f58f8c61ed56d6d/app/subscribers/solidus_stripe/webhook/payment_intent_subscriber.rb#L69) if the payment has already been voided.
- `charge.refunded` will sync all refunds in an idempotent way once #281 is merged.

At least for this initial release, it can be an acceptable compromise to ship with nothing more robust at a higher level. In order to provide enough flexibility for a user to build their own system, we could modify omnes to allow [adapters](https://github.com/nebulab/omnes#adapters) to be configured at the subscriber class level and have a top-level subscriber class for Stripe webhook handling.

**Comment by waiting-for-dev** [comment]
With #285, we also acknowledge race conditions for duplicated events. Once that's merged, we can close this issue and re-take the work on the topic if we find time to work on configuring subscriber-level adapters on Omnes (which shouldn't be a great effort).
