### ISSUE TITLE
Properly handle old payments 

### ISSUE THREAD

**Issue by elia** [solidusio-contrib/solidus_stripe#200]
We need to ensure old payments are cleared out either by us or by the `after_create :invalidate_old_payments` callback on Spree::Payment.

> because you transition payment directly to processing at line 90, you might have an old payment in `processing` state that you will here try to invalidate. Processing payments cannot be invalidated so this line can fails. Maybe you could try both `void` (or cancel?) and `invalidate` with something like 

``` 
old_payments.each do |old_payment|
           old_payment.invalidate! if old_payment.can_invalidate?
           old_payment.void! if old_payment.can_void?
end
```

_Originally posted by @loicginoux in https://github.com/solidusio/solidus_stripe/pull/158#discussion_r1117488049_

**Comment by elia** [comment]
We since switched to a different approach and the code on which the original comment was posted is no longer there.

**Comment by loicginoux** [comment]
ok can be closed, I'd say
