### ISSUE TITLE
QA the documentation

### ISSUE THREAD

**Issue by elia** [solidusio-contrib/solidus_stripe#208]
## Why

We need to ensure all options and tradeoffs are clear to users, as well as the limitations of the default setup.

## What

This includes:
~- payment/setup intents difference~
~- skipping the confirm step~

- [x] authorizing at the ~payment~ confirm step
- [x] implications for non card methods and Europe
- [x] how to migrate to the new extension
- [x] how to integrate with a different frontend

**Comment by chrean** [comment]
We can make the README as good as possible to keep documentation as close to the code as possible.
Then we may add a page in the guides with some basic information and a link to the README.
