### ISSUE TITLE
Consider scoping all payment method routes to its slug

### ISSUE THREAD

**Issue by waiting-for-dev** [solidusio-contrib/solidus_stripe#220]
## What

On #213, we introduced a slug to differentiate webhook endpoints for different Stripe payment method instances. We can consider using it for the rest of the payment method requests (actions on the Stripe callback controller).

- [ ] share the slug with the intents controller
- [ ] listen for webhooks as part of `bin/dev`
- [ ] support an env variable for the slug similarly to how we setup the payment method in the initializer

## Why

That would be more consistent. Conversely, it could make sense only to use the slug when there's a compelling reason and use Rails' default `:id` param otherwise. See https://github.com/solidusio/solidus_stripe/pull/213#discussion_r1131411856 for the complete discussion.

**Comment by elia** [comment]
Taking this up also as a way to improve the DX when testing webhooks locally:
- listen for webhooks as part of `bin/dev`
- support an env variable for the slug similarly to how we setup the payment method in the initializer
