### ISSUE TITLE
Error when completing an order with a potential fraudulent payment

### ISSUE THREAD

**Issue by waiting-for-dev** [solidusio-contrib/solidus_stripe#224]
**Steps to reproduce**

- Perform a checkout and use [card number 4100000000000019](https://stripe.com/docs/testing#fraud-prevention) to pay with Stripe.
- The order advances successfully from the payment to the confirm step. However, when clicking on the "Complete" button (i.e., when Stripe tries to authorize the payment intent), a `Stripe::CardError` is raised.

[screencast-localhost_3000-2023.03.17-09_27_55.webm](https://user-images.githubusercontent.com/52650/225869555-47d6b55a-cc4f-454d-befa-04c68f7ab094.mp4)

**Comment by rainerdema** [comment]
After more investigation, I've found that the following cards fail with the same exception:
| Number| Description | Source |
|--------|--------|------------|
| 4100000000000019 | The charge has a [risk level of “highest”](https://stripe.com/docs/radar/risk-evaluation#high-risk). Radar always blocks it.| [Stripe Fraud Prevention Testing](https://stripe.com/docs/testing?testing-method=card-numbers#fraud-prevention) |
| 4000000000004954 | The charge has a [risk level of “highest”](https://stripe.com/docs/radar/risk-evaluation#high-risk). Radar might block it [depending on your settings](https://stripe.com/docs/radar/risk-settings). | [Stripe Fraud Prevention Testing](https://stripe.com/docs/testing?testing-method=card-numbers#fraud-prevention) |
| 4000000000000341 | Attaching this card to a [Customer](https://stripe.com/docs/api/customers) object succeeds, but attempts to charge the customer fail. | [Stripe Declined Payments Testing](https://stripe.com/docs/testing?testing-method=card-numbers#declined-payments) |

Note: In my case, these only fail with setup intent configured during the payment intent creation.
