### ISSUE TITLE
Does an api key should be in a payment method preference ?

### ISSUE THREAD

**Issue by loicginoux** [solidusio-contrib/solidus_stripe#225]
**Desired Behavior**
Maybe it's just me but It does not seem right we have to enter manually the Stripe API key in the configuration of the payment method. it does not look too secure for different reason: 
- it will be printed in logs 
- it will be stored in DB.
- anyone with access to this page can access the api key.

I understand you can use the preference source `solidus_stripe_env_credentials` that will take the API from env credentials.
I understand you may need to support multiple stripe payment methods and in this case multiple env variable does not work.
But if I want to change other preferences like the `stripe_intents_flow` or the `setup_future_usage`, I don't have other choice that to pass by the custom preference source, and pass the stripe api key along.

Not sure what's the solution yet. It would be easier if to not support multiple SolidusStripe::PaymentMethod but I don't know if this is an option or not.

**(Optional) Current Behavior**

![Screenshot 2023-03-17 at 10 12 42](https://user-images.githubusercontent.com/824936/225862215-59b30088-8ba7-45a6-9c97-cc7cfb718d5d.png)

**Comment by waiting-for-dev** [comment]
> I understand you can use the preference source solidus_stripe_env_credentials that will take the API from env credentials.

Yeah, that's the solution.

> I understand you may need to support multiple stripe payment methods and in this case multiple env variable does not work.

You can indeed use different env variables for each payment method, as you can create as many sources as you want:

```ruby
# config/initializers/solidus_stripe.rb
  Spree::Config.static_model_preferences.add(
    'SolidusStripe::PaymentMethod',
    'solidus_stripe_env_credentials_one',
    api_key: ENV.fetch('SOLIDUS_STRIPE_API_KEY_ONE'),
    publishable_key: ENV.fetch('SOLIDUS_STRIPE_PUBLISHABLE_KEY_ONE'),
    test_mode: ENV.fetch('SOLIDUS_STRIPE_API_KEY_ONE').start_with?('sk_test_'),
    webhook_endpoint_signing_secret: ENV.fetch('SOLIDUS_STRIPE_WEBHOOK_SIGNING_SECRET_ONE')
  )

  Spree::Config.static_model_preferences.add(
    'SolidusStripe::PaymentMethod',
    'solidus_stripe_env_credentials_two',
    api_key: ENV.fetch('SOLIDUS_STRIPE_API_KEY_TWO'),
    publishable_key: ENV.fetch('SOLIDUS_STRIPE_PUBLISHABLE_KEY_TWO'),
    test_mode: ENV.fetch('SOLIDUS_STRIPE_API_KEY_TWO').start_with?('sk_test_'),
    webhook_endpoint_signing_secret: ENV.fetch('SOLIDUS_STRIPE_WEBHOOK_SIGNING_SECRET_TWO')
  )
```

> But if I want to change other preferences like the stripe_intents_flow or the setup_future_usage, I don't have other choice that to pass by the custom preference source, and pass the stripe api key along.

You can add that preferences to the configured source. It's only that, for now, they aren't being added into the generated initializer:

```ruby
  Spree::Config.static_model_preferences.add(
    'SolidusStripe::PaymentMethod',
    'solidus_stripe_env_credentials_one',
    api_key: ENV.fetch('SOLIDUS_STRIPE_API_KEY_ONE'),
    publishable_key: ENV.fetch('SOLIDUS_STRIPE_PUBLISHABLE_KEY_ONE'),
    test_mode: ENV.fetch('SOLIDUS_STRIPE_API_KEY_ONE').start_with?('sk_test_'),
    webhook_endpoint_signing_secret: ENV.fetch('SOLIDUS_STRIPE_WEBHOOK_SIGNING_SECRET_ONE'),
    sripe_intent_flow: 'payment'
  )
```

Does all of that make sense? :slightly_smiling_face:

**Comment by loicginoux** [comment]
ah ok I see. Perfect, thanks. Probably my fault and I missed some documentation about it.

**Comment by waiting-for-dev** [comment]
No worries, that's arguably a bit complex and weird part. We have some docs [here](https://guides.solidus.io/advanced-solidus/model-preferences#payment-methods), but don't hesitate to ask if something is not clear.
