### ISSUE TITLE
Handle `charge.succeeded` or `payment_intent.amount_capturable_updated` webhook event

### ISSUE THREAD

**Issue by loicginoux** [solidusio-contrib/solidus_stripe#228]
related to https://github.com/solidusio/solidus_stripe/issues/179
whenever an order is completed through a regular checkout (the intent is comfirmed from front end) and a payment method has a preference `auto_capture: off`, the event `payment_intent.succeeded` is not yet sent to solidus (because the capture is not yet done)

Instead these events are sent
- `charge.succeeded`
- `payment_intent.amount_capturable_updated`

Not sure which one is the best candidate to listen to between the 2, but I would say at this stage the order's payment should be passed to `pending` until manual capture is done.

**Comment by waiting-for-dev** [comment]
@loicginoux, unless I'm missing something, we don't need to do anything as the payment will already be in the `pending` state.

**Comment by loicginoux** [comment]
I'll check again, it might be due to the customisation of my own app. In my case, the payment is in the initial state `checkout`  when rendering the checkout page. I'll close the issue if necessary

**Comment by loicginoux** [comment]
I checked again the current implementation of the gem and indeed, it is not the case for solidus_stripe workflow, so forget my first comment and we can close this issue.
I still have a question, that we are trying to answer and that may also need some work on the gem depending on your opinion on the matter.
If I summarize the current behaviour of the gem after payment

1- user confirm payment on page.
2- payment confirmation is sent to stripe by front end with a return url 
3- return url is `SolidusStripe::IntentsController#payment_confirmation` (or setup_confirmation)
4 - the controller creates a payment in pending and pass the order in the state confirm or complete. (let's say complete for the example)
5 - Stripe sends the webhook to PaymentIntentSubscriber that will complete the payment if not yet completed.


Questions:
A- what's happening if stripe sends webhook 30min, 1h, etc... later ? what do you present to the users while waiting ?
B- what's happening if stripe never sends webhook ? (not sure if this is a realistic case, can it happen ?)
C- what's happening if stripe sends webhook before solidus has created the payment on the return url ? 
D- what's happening if stripe sends an payment error on webhook ? the subscriber is not yet implemented yet but the payment will be passed from pending to failed and the issue is that order is already in completed state. is that not a problem for the order's state ?

I'm curious to know your thoughts on these edge cases.
If necessary other issues can be created to handle specific cases, and I'll close this one.

**Comment by waiting-for-dev** [comment]
> 5 - Stripe sends the webhook to PaymentIntentSubscriber that will complete the payment if not yet completed.

For now, that's not happening automatically. Users need to manually capture the payment. But, yeah, that will be an option when #178 is done.

> A- what's happening if stripe sends webhook 30min, 1h, etc... later ? what do you present to the users while waiting ?

Once the payment is authorized, users see a summary of their completed order. On Solidus, the order may be completed while its payment is still waiting to be captured. Once Stripe updates us, we complete the payment on Solidus. You can check yourself using the sandbox application within the gem (from the root `bin/rails server`). You'll be able to complete the order and you'll see a success message. Then, you need to go to Stripe to capture the payment (again, that's the only flow until #178 is done).

> B- what's happening if stripe never sends webhook ? (not sure if this is a realistic case, can it happen ?)

I don't know if that could happen, but Stripe recommends using webhook to update the system, and that's what we're doing. Regardless, a payment can also be captured from Solidus' admin panel, and it'll also call Stripe's API.

> C- what's happening if stripe sends webhook before solidus has created the payment on the return URL ?

That's something we still need to figure out (see #190)

> D- what's happening if stripe sends an payment error on webhook ? the subscriber is not yet implemented yet but the payment will be passed from pending to failed and the issue is that order is already in completed state. is that not a problem for the order's state ?

That's a good point. Solidus rolls back the order to the `payment` state on authorization failure. I'm not sure where that's handled, but we need to make sure that's also happens via webhook on #184.

**Comment by waiting-for-dev** [comment]
> D- what's happening if stripe sends an payment error on webhook ? the subscriber is not yet implemented yet but the payment will be passed from pending to failed and the issue is that order is already in completed state. is that not a problem for the order's state ?

I confirm that the order needs to keep being on the `completed` state. That's what vanilla Solidus does, so we should do the same. You must look at the order and payment state as two different things. An order is actually done when both the order and the payments are done.

**Comment by waiting-for-dev** [comment]
Closing it as you confirmed it's not an issue. Please, feel free to follow up with new questions if needed.
