### ISSUE TITLE
Detect refunds that have already been performed

### ISSUE THREAD

**Issue by waiting-for-dev** [solidusio-contrib/solidus_stripe#262]
On #180, we're handling the `charge.refunded` webhook event to generate a `Spree::Refund` copy. However, we're not checking whether the incoming webhook has already been processed in the past.

Although we're skipping the processing when the associated payment has already been fully refunded, it might be the case that we handle twice a partial amount refund. As noted in a [comment from the referenced issue](https://github.com/solidusio/solidus_stripe/issues/180#issuecomment-1484807184), we can't use the transaction ARN as that's something not always available at the moment the event is created.

There're two ways to handle that:

- Generally, through #188, making the system resilient against duplicated webhook events.
- Specifically, as another layer of security, associating every created refund with the charge id in another database table.

Another scenario for a duplicated refund would be one that has been initiated by Solidus, calling the Stripe API and getting the corresponding webhook event.

**Comment by kennyadsl** [comment]
We can probably explore saving the id of the Stripe refund on the Solidus Refund in the `transaction_id` field. When the webhook comes, we could check if there's an existing refund and skip creating it on our end if so.

**Comment by waiting-for-dev** [comment]
That could work. We'd need to save it both when we create a refund from Solidus admin and when we create it from an incoming webhook.

**Comment by waiting-for-dev** [comment]
> We can probably explore saving the id of the Stripe refund on the Solidus Refund in the transaction_id field. 

The solution is trickier than expected. The problem is that Stripe doesn't add the created refund id on the event it sends when there's a refund (`charge.refunded`).

The best we can do is use the charge id to fetch all the refunds associated with it (`Stripe::Refund.list(charge: charge_id`) and create a refund on Solidus for all of the Stripe refunds that are not already present. That's to say, a `charge.refunded` event would handle all concurrent refunds: in the case of two partial refunds happening at the same time for a given order, the first `charge.refunded` event would trigger the creation of the two Solidus refunds, while the second one would do nothing.

Still, there's something else to consider. As we said in previous comments, a refund generated from Solidus will call the Stripe API and create a refund there, which in turn will publish the `charge.refunded` event. When we get the response from the Stripe API, we can update the Solidus refund `transaction_id` field with the Stripe refund id. However, there's no guarantee that, in the meantime, we haven't already processed the webhook (i.e., before updating the refund, therefore ending up with two records). We can workaround like this:
- Before calling the Stripe API, use a value `[[PENDING]]` for the created Solidus refund `transaction_id`.
- Once we get the response from the API, update `transaction_id` with the actual refund id.
- Have the `charge.refunded` webhook handler described above:
  - Do nothing when we have a Solidus refund with `[[PENDING]]` transaction id, as we expect it to be populated by our gateway once it processes the Stripe API response.
  - Still, retry a number of times (ideally, until `[[PENDING]]` is updated) if there are other concurrent partial Stripe refunds waiting to be processed, as we can't know for sure which one corresponds to the pending one if they share the same amount.

**Comment by elia** [comment]
@waiting-for-dev what if we combine the transaction_id with setting a "solidus id" in the stripe refund metadata?

1. For solidus initiated refunds we can [set the metadata at creation time](https://stripe.com/docs/api/refunds/create#create_refund-metadata)
2. For stripe initiated ones we can create the solidus counterpart and [update the stripe refund's metadata field](https://stripe.com/docs/api/refunds/update#update_refund-metadata)

This way if a webhook comes in with an already present metadata solidus id we can immediately match it to its counterpart, and if it's missing we'll know we need to create a Spree::Refund to match it.

**Comment by waiting-for-dev** [comment]
Thanks for your feedback, @elia. That's a great suggestion. For Stripe-generated refunds, there's, in fact, no need to update their metadata fields in any way. Just checking that their id is already in our database as a `transaction_id` is enough. However, leveraging metadata for the refunds generated from Solidus avoids using the ugly `[[PENDING]]` hack. Instead of sending the Solidus id, which could become brittle in the face of database migrations, we can just use a `skip_solidus_sync: "true"` "boolean" flag. I have already tried it, and it works like a charm :raised_hands:
