### ISSUE TITLE
Support creating payments from admin

### ISSUE THREAD

**Issue by elia** [solidusio-contrib/solidus_stripe#266]
## Why

Solidus supports payment creation from the /admin, usually done by the customer support team.

```[tasklist]
### This payment creation can be done in two ways
- [ ] https://github.com/solidusio/solidus_stripe/issues/279
- [ ] https://github.com/solidusio/solidus_stripe/issues/280
```

## What

Implement the payment form and required methods (e.g. authorize/purchase in the gateway). Supporting payment intents that will require additional actions from the customer can be left out, as long as it's properly documented in the readme.

**Comment by rainerdema** [comment]
Closing in favor of #279, #280
