### ISSUE TITLE
[v4.4] Migration does not update all `Spree::Preference`s used by `solidus_gateway`

### ISSUE THREAD

**Issue by benjaminwil** [solidusio-contrib/solidus_stripe#273]
The migration `20181010123508_update_stripe_payment_method_type_to_credit_card.solidus_stripe.rb` includes a step to update all `Spree:Preference` records keys from "spree/gateway/stripe_gateway" to "spree/payment_method/stripe_credit_card".

However, when I manually run the query in the migration:

```ruby
Spree::Preference.where("#{ActiveRecord::Base.connection.quote_column_name('key')} LIKE 'spree/gateway/stripe_gateway'")
```

It returns an empty array, even though I know I have preferences that contain "spree/gateway/stripe_gateway" as a substring.

I think that the query should instead read as:

```diff
- Spree::Preference.where("#{ActiveRecord::Base.connection.quote_column_name('key')} LIKE 'spree/gateway/stripe_gateway'")
+ Spree::Preference.where("#{ActiveRecord::Base.connection.quote_column_name('key')} LIKE 'spree/gateway/stripe_gateway%'")
```

**Solidus Version**:

2.11.17

**To Reproduce**

1. Create a `Spree::Preference` with a key like `spree/gateway/stripe_gateway/server/1`.
2. Run the migration.
3. Check to see if the `Spree::Preference` key has been updated to have `spree/payment_method/stripe_credit_card/server/1`.

**Current behavior**

The key is not updated.

**Expected behavior**

The key is updated.

**Screenshots**

N/A

**Additional context**

We're using MariaDB (MySQL).

**Comment by kennyadsl** [comment]
@benjaminwil seems legit; feel free to open a PR for this (for `v3` and `v4` branches only)!

**Comment by benjaminwil** [comment]
Sounds good. I am unsure what the right thing to do is. I wonder if anyone has opinions:

1. Fix the old migration, as anyone who has already run it has likely started using `solidus_stripe` in production and handled any issues themselves.
2. Create a new migration, and leave a note in the CHANGELOG that there's a new data migration that will update preferences for old `solidus_gateway` payment methods.

**Comment by kennyadsl** [comment]
I'd go with 1 considering that if this was an issue, people already fixed that by themselves as you pointed out.

**Comment by benjaminwil** [comment]
Resolved
