### ISSUE TITLE
Consolidate naming for Solidus/Stripe payment methods

### ISSUE THREAD

**Issue by waiting-for-dev** [solidusio-contrib/solidus_stripe#283]
**Desired Behavior**

We have a naming collision between Solidus payment methods & Stripe payment methods. We're not consistent across the code based on how we reference one or the other. That could lead to confusion in some cases.

We can scan the code base and establish a pattern with a relatively low effort.

**Comment by elia** [comment]
@waiting-for-dev for the sake of clarity can you provide some examples?

**Comment by waiting-for-dev** [comment]
> @waiting-for-dev for the sake of clarity can you provide some examples?

- https://github.com/solidusio/solidus_stripe/blob/b04dedd596b22ac8616ba037a862daaf7f453965/lib/solidus_stripe/webhook/event.rb#L56
- https://github.com/solidusio/solidus_stripe/blob/b04dedd596b22ac8616ba037a862daaf7f453965/app/controllers/solidus_stripe/intents_controller.rb#L8

Not sure if the impact is high, but I've been confused in the past, probably mainly in tests.

**Comment by elia** [comment]
@waiting-for-dev thank you, makes sense, I would say, that living within solidus (aka spree) we should only specify when it's something from stripe, would that work?

**Comment by waiting-for-dev** [comment]
:100:
